### ISSUE TITLE
User

### ISSUE THREAD

**Issue by rnackman** [mplusmuseum/mplusmuseum-www#86] opened 2017-12-08 18:37 UTC
- [ ] Profile
- [ ] Account/Settings
- [ ] Role

**Comment by revdancatt** [comment] 2018-02-05 10:39
Is there any more documentation on this? Connected to/duplicate of #96?

**Comment by erchaves** [comment] 2018-03-15 23:25
Closing this for now - we can recreate from a proper spec later after we get UX.

**Closed by erchaves** 2018-03-15 23:25 UTC
Labels: components, question, task
